### ISSUE TITLE
Scraping all sounds from German Wiktionary (Feature Request)

### ISSUE THREAD

**Issue by FyTpodQUuWvQNTh** [gambolputty/wiktionary-de-parser#4]
@gambolputty   @alanderex 

**Is it possible with the Python script to obtain a list with all the sound URLs of the German Wiktionary ?**

I would like to obtain a .txt file with all the audio links to download them. As an example, the word "Katze" contains 3 audios that I would like to grab:  https://de.wiktionary.org/wiki/Katze

My intention is to download ALL the sounds to make a “Pronunciation Dictionary” for GoldenDict and distribute it freely to language learners. 

_Thanks in advance !_

-------
_Unfortunately, I don't know Python and  cannot make a Pull Request right now. However, if you consider possible to edit the Python script I could try to learn Python just to do it._

**Comment by gambolputty** [comment]
Hey @alanderex,

thanks for taking an interest in this module! It is possible to [add new extraction methods](https://github.com/gambolputty/wiktionary-de-parser#adding-new-extraction-methods) to the parser. This way you could, for example, parse the Wikitext markup yourself and extract the pieces you need to obtain the URLs of the audio files. 
There are some Python modules (for example, [this one](https://github.com/earwig/mwparserfromhell)) that make parsing Wikitext a little less frustrating.

Unfortunately, I cannot offer any practical help or solution here. 

Regards,
Gregor
