### ISSUE TITLE
Wrong syllables entries

### ISSUE THREAD

**Issue by miasbeck** [gambolputty/wiktionary-de-parser#7]
It looks like the "syllables" of some records were not parsed correctly. 

Sometimes there is only one single-letter entry where there should be several:

title: 'nutzlose'
syllables: ['n']

title: 'mitgegangen, mitgefangen'
syllables: ['m']

Sometimes there is a comma left:

title: 'A'
syllables: ['A,']

title: 'X'
syllables: ['X,']

**Comment by gambolputty** [comment]
Thanks for your bug report!

I improved syllables parsing and added tests. I just released a new version and the issues above should be fixed by now: `pip install wiktionary-de-parser`
